<?php
/**
 * Created By PhpStorm
 * User: Pony
 * Data: 2023/11/21
 * Time: 13:54
 */
declare(strict_types=1);

namespace App\Controllers\Api;

use App\Controllers\Base as BaseController;
use App\Enums\Code;
use CodeIgniter\API\ResponseTrait;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use OutOfRangeException;
use Psr\Log\LoggerInterface;

class Base extends BaseController
{
    use ResponseTrait;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger): void
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    /**
     * 渲染数据
     * @param array|string $data
     * @return ResponseInterface
     */
    protected function render(array|string $data = []): ResponseInterface
    {
        $resp = [
            'OK' => 'OK',
            'code' => Code::OK,
            'message' => '',
            'data' => []
        ];
        if (is_string($data)) {
            $resp['message'] = $data;
        }
        if (is_array($data)) {
            $code = $data['code'] ?? Code::FAIL;
            try {
                if (!is_object($code)) {
                    throw new OutOfRangeException();
                }
                $resp['code'] = $code->value;
            } catch (OutOfRangeException $exc) {
                log_message('error', $exc->getMessage());
                $resp['code'] = Code::FAIL->value;
            }
            if ($resp['code']) {
                unset($resp['OK']);
            }
            $resp['message'] = $data['message'] ?? ($data['code'] ?? Code::FAIL)->name;
            unset($data['code']);
            unset($data['message']);
            if (!empty($data)) {
                $resp['data'] = $data;
            } else {
                unset($resp['data']);
            }
        }
        return $this->respond($resp, 200);
    }
}